---
Name: silverstripe-opauth
---
WSE\Opauth\OpauthAuthenticator:
  opauth_settings:
    security_iteration: 500
    security_timeout: '2 minutes'
    callback_transport: 'session'
SilverStripe\Security\Member:
  has_many:
    OpauthIdentities: WSE\Opauth\OpauthIdentity
