---
Name: opauthroutes
After: framework/routes#rootroutes
---
# Config weirdness - confusing.
# Remember to replicate this path with no slashes in the Director rules.
WSE\Opauth\OpauthController:
  opauth_path: '/opauth/'
SilverStripe\Control\Director:
  rules:
    'opauth/strategy/$Strategy/$StrategyMethod': 'WSE\Opauth\OpauthController'
    'opauth/strategy/$Strategy': 'WSE\Opauth\OpauthController'
    'opauth': 'WSE\Opauth\OpauthController'
